# Generated by Django 3.1.3 on 2020-11-21 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='Nothing', max_length=50)),
                ('password', models.CharField(default='Nothing', max_length=50)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nothing', max_length=50)),
                ('phone', models.BigIntegerField(default=0)),
                ('email', models.CharField(default='Nothing', max_length=50)),
                ('Address', models.CharField(default='Nothing', max_length=50)),
                ('emp_image', models.FileField(blank=True, upload_to='media')),
                ('gender', models.CharField(default='Nothing', max_length=50)),
                ('log_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.login')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
