# Generated by Django 3.1.3 on 2020-11-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default='Nothing', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='Nothing', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='pincode',
            field=models.CharField(default='Nothing', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(default='Nothing', max_length=50),
        ),
    ]
