# Generated by Django 3.1.3 on 2020-11-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20201122_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.CharField(default='Nothing', max_length=50),
        ),
    ]
