# Generated by Django 3.1.3 on 2020-11-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_employee_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='role',
            field=models.CharField(default='Nothing', max_length=50),
        ),
    ]
